version: '3.7'

services:
  web:
    build: docker/development
    environment:
      NODE_PATH: /app/signin-wall
      VIRTUAL_HOST: gpay.localtest.me
      VIRTUAL_PORT: 3000
    ports:
      - "4000:3000"
    networks:
      default:
        aliases:
          - gpay.localtest.me
      proxy:
        aliases:
          - gpay.localtest.me
    volumes:
      - .:/app

networks:
  proxy:
    external: true
